version: "3"

networks:
  datashot:

services:
  mysql56:
    platform: linux/amd64
    image: mysql:5.6.40
    container_name: datashot-mysql56
    ports:
      - 3356:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL56_PASSWORD
    networks:
      - datashot

  mysql57:
    platform: linux/amd64
    image: mysql:5.7.26
    container_name: datashot-mysql57
    ports:
      - 3357:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL56_PASSWORD
    networks:
      - datashot

  mysql80:
    image: mysql:8.0.33
    container_name: datashot-mysql80
    ports:
      - 3380:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL56_PASSWORD
    networks:
      - datashot

  php:
    build:
      context: .
      dockerfile: docker/work/Dockerfile
    container_name: datashot-php
    environment:
      PHP_IDE_CONFIG: serverName=datashot-php
    volumes:
       - ./:/datashot
    networks:
      - datashot
    entrypoint: php
